version: "3.9"

services:
  restaurant:
    container_name: restaurant-bogo-api
    build: .
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGO_URI: "mongodb+srv://restaurantDB:Vancouver%40123@bogo-ninja-restaurant-d.cgzrq.mongodb.net/?retryWrites=true&w=majority&appName=bogo-ninja-restaurant-db"
